name: release

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.26
      with:
        github_token: ${{ secrets.TOKEN }}
        goversion: https://go.dev/dl/go1.17.7.linux-amd64.tar.gz
        project_path: "./cmd/impi"
        binary_name: "impi"
        goos: linux
        goarch: amd64
